name: ZelekOgloszenia
version: 1.0
main: pl.zelek.ogloszenia.Main
commands:
  ogloszenie:
    description: Wysyła ogłoszenie jako TITLE do wszystkich graczy
    usage: /<command> [treść]
  ogloszeniereload:
    description: Przeładowuje config.yml w locie
    usage: /<command>
permissions:
  ogloszenie.use:
    description: Pozwala używać komendy /ogloszenie
    default: op
  ogloszenie.reload:
    description: Pozwala przeładować config bez restartu
    default: op
